services:
  github-runner-windows:
    image:  myoung34/github-runner:latest
    container_name: ${RUNNER_CONTAINER_NAME:-github-runner} 
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      # - /var/run/docker.sock:/var/run/docker.sock
      - ${LOCATION_TMP}${REPO_NAME}:/tmp/${REPO_NAME}
      - ${LOCATION_TMP}action-runner-files:/actions-runner-files
    command: >
      bash -c "./config.sh --url $REPO_URL --token ${GITHUB_RUNNER_TOKEN} && ./run.sh"